#!/usr/bin/env bash
set -e
# Usage: fs ci [<branch>]
# Summary: Open branch CI page in browser
# Help: This can be used to open current branch (or any specified branch) on CI (Semaphore)
# Requires `ci` parameter to be set in `.fs.yml`.
# Examples:
#
#    fs ci            # opens current branch on CI
#    fs ci master     # opens "master" branch on CI

case $1 in
  "" )
    current_branch=$(git rev-parse --abbrev-ref HEAD)
  ;;
# Provide fs completions
  "--complete" )
    git branch | sed 's/* /  /' | awk '{print $1}'
    exit
  ;;
  * )
    current_branch=$1
  ;;
esac

BRANCH_NAME=$current_branch
branch_name=$(echo $current_branch | tr '[:upper:]' '[:lower:]')

ci_url=$(grep "ci:" .fs.yml | sed 's/ci://' | sed 's/"//g' | tr -d ' ')
ci_url=$(echo $ci_url | sed "s/%{branch}/$branch_name/" | sed "s/%{BRANCH}/$BRANCH_NAME/")

fs-open $ci_url
