#!/usr/bin/env bash
# Usage: fs gh [subcommand]
# Summary: Open current github repo in browser
# Help: This can be used to open current repo on github. Available subcommands:
#
#    fs gh                           # opens current repo on github
#    fs gh pulls (fs gh p)           # opens current repo's pull requests on github
#    fs gh issues (fs gh i)          # opens current repo's issues on github
#    fs gh pulls new (fs gh p n)     # opens new pull request in current repo on github
#    fs gh issues new (fs gh i n)    # opens new issue in current repo on github
#    fs gh pulls closed (fs gh p c)  # opens current repo's closed pull requests on github
#    fs gh issues closed (fs gh i c) # opens current repo's closed issues on github
#    fs gh search (fs gh s) <query>  # searches in current repo

github_repo=$(git remote -v | grep fetch | sed 's/.*github\.com[:/]\(.*\)\.git.*/\1/')

function open_github {
  open "https://github.com/$github_repo/$1"
}

function process_pulls {
  case $1 in
    "" )
      open_github "pulls?state=open";;
    "new" | "n" )
      branch_name=$(git rev-parse --abbrev-ref HEAD)
      open_github "compare/$branch_name";;
    "closed" | "c" )
      open_github "pulls?state=closed";;
  esac
}

function process_issues {
  case $1 in
    "" )
      open_github "issues?state=open";;
    "new" | "n" )
      open_github "issues/new";;
    "closed" | "c" )
      open_github "issues?state=closed";;
  esac
}

case $1 in
  "" )
    open_github;;
  "pulls" | "p" )
    process_pulls $2;;
  "issues" | "i" )
    process_issues $2;;
  "search" | "s" )
    open_github "search?q=$2";;
# FIXME: second level completion is broken - https://github.com/basecamp/sub/issues/7
# Provide fs completions
  "--complete" )
    echo pulls
    echo issues
    echo search
    ;;
esac
