#!/usr/bin/env ruby
# Usage: fs ssh [<application>] [<environment>]
# Summary: Open SSH session to a given application (environment)
# Help: Open SSH session to a given application (environment).
# Uses per-project or per-user configuration stored in `.fs.yml`, see README.md for examples.

require File.join(ENV['_FS_ROOT'], 'share', 'fs', 'lib', 'fs_tool')

ssh_manager = FsTool::SshCommandManager.new

# Provide fs completions
if ARGV[0] == '--complete'
  puts ssh_manager.completions
else
  begin
    ssh_manager.process(*ARGV)
  rescue FsTool::ServerNotFoundException
    $stderr.puts('unknown application or environment')
  end
end
