#!/usr/bin/env bash
# Usage: fs setup <project-type> <project-name>
# Summary: Bootstrap new project from fs/xxx-base templates
# Help: Bootstrap new project from fs/xxx-base templates. Examples:
#  fs setup rails <project name>  # setup new project using rails-base template
#  fs setup api <project name>    # setup new project using rails-base-api template
#  fs setup static <project name> # setup new project using static-base template
