#!/usr/bin/env ruby
# Usage: fs ssh [<application>] [<environment>]
# Summary: Open SSH session to a given application (environment)
# Help: Open SSH session to a given application (environment).
# Uses per-project or per-user configuration stored in `.fs.yml`, see README.md for examples.
# Examples:
#
# fs ssh staging # open SSH session to the current application's staging server
# fs ssh home    # open SSH session to the 'home' server

require File.join(ENV['_FS_ROOT'], 'share/fs/lib/fs_tool')

ssh_manager = FsTool::SshCommandManager.new

# Provide fs completions
if ARGV[0] == '--complete'
  puts ssh_manager.completions
  exit
end


server, params = ssh_manager.parse(*ARGV)

if server
  server.open_ssh_session
else
  $stderr.puts('unknown application or environment')
end
