#!/usr/bin/env ruby
# Usage: fs tail [<application>] [<environment>]
# Summary: Display the recent application logs in realtime
# Help: Display the recent application logs in realtime.
# Uses per-project or per-user configuration stored in `.fs.yml`, see README.md for examples.
# Examples:
#
# fs tail staging                 # display remote application logs
# fs tail staging delayed_job.log # display remote delayed job logs
# fs tail                         # display local application logs

require File.join(ENV['_FS_ROOT'], 'share/fs/lib/fs_tool')

ssh_manager = FsTool::SshCommandManager.new

# Provide fs completions
if ARGV[0] == '--complete'
  puts ssh_manager.completions
  exit
end


server, params = ssh_manager.parse(*ARGV)

if server
  if params.args.empty?
    server.run("tail -f log/#{params.environment}.log")
  else
    files = params.args.map { |name| "log/#{name}" }
    server.run("tail -f #{files.join(' ')}")
  end
else
  exec('tail -f log/*.log')
end
